
#include "bpf_shim.h"
#define MAT_DIM 4
#define MAT_SIZE (MAT_DIM * MAT_DIM)
int main() {
    void *mat_map_1 = MAP_BY_FD(0), *mat_map_2 = MAP_BY_FD(1), *mat_map_res = MAP_BY_FD(2), *result;
    int mat_1[MAT_SIZE], mat_2[MAT_SIZE], mat_res[MAT_SIZE];
    int i, j, k;


    i = 0;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 1;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 2;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 3;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 4;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 5;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 6;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 7;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 8;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 9;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 10;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 11;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 12;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 13;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 14;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;
    i = 15;
    result = bpf_map_lookup_elem(mat_map_1, &i);
    mat_1[i] = *(int *)result;
    result = bpf_map_lookup_elem(mat_map_2, &i);
    mat_2[i] = *(int *)result;

    i = 0, j = 0;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 0, j = 1;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 0, j = 2;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 0, j = 3;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 1, j = 0;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 1, j = 1;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 1, j = 2;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 1, j = 3;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 2, j = 0;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 2, j = 1;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 2, j = 2;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 2, j = 3;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 3, j = 0;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 3, j = 1;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 3, j = 2;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];

    i = 3, j = 3;
    mat_res[i * MAT_DIM + j] = 0;
    k = 0;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 1;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 2;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    k = 3;
    mat_res[i * MAT_DIM + j] += mat_1[i * MAT_DIM + k] * mat_2[k * MAT_DIM + j];
    i = 0;
    bpf_map_update_elem(mat_map_res, &i, &mat_res[i], 0);
    i = 1;
    bpf_map_update_elem(mat_map_res, &i, &mat_res[i], 0);
    i = 2;
    bpf_map_update_elem(mat_map_res, &i, &mat_res[i], 0);
    i = 3;
    bpf_map_update_elem(mat_map_res, &i, &mat_res[i], 0);
    return 0;
}
