from dataclasses import replace
from machine_profile import MachineProfile

# NOEL-V FPGA soft-core
NOELV_PROFILE = MachineProfile(
    name="noelv",
    latency=None,
    line_size_bytes=32,
    l1_associativity=1,
    l1_hit_cycles=3,
    l2_associativity=8,
    l2_hit_cycles=16,
    l3_associativity=None,
    l3_hit_cycles=None,
    miss_cycles=60,
    cpu_freq_hz=1e8,
    cache_size=12,
    default_helper_call_cost=150,
    iter_new_cycles=28,
    iter_next_cycles=15,
    iter_destroy_cycles=7,
    map_lookup_cycles=95,
    map_update_cycles=105,
    map_delete_cycles=15,
    math_sqrt_cycles=198,
    math_sin_cycles=873,
    math_cos_cycles=477,
    math_atan2_cycles=1488,
    latency_overrides={
        "ADD64_K": 20,
        "ADD64_X": 5,
        "ADD_K": 20,
        "ADD_X": 5,
        "AND64_K": 20,
        "AND64_X": 8,
        "AND_K": 20,
        "AND_X": 8,
        "ARSH64_K": 1,
        "ARSH64_X": 8,
        "ARSH_K": 1,
        "ARSH_X": 8,
        "ATOMIC_ADD_DW": 8,
        "ATOMIC_ADD_FETCH_DW": 8,
        "ATOMIC_ADD_FETCH_W": 8,
        "ATOMIC_ADD_W": 8,
        "ATOMIC_AND_DW": 8,
        "ATOMIC_AND_FETCH_DW": 8,
        "ATOMIC_AND_FETCH_W": 8,
        "ATOMIC_AND_W": 8,
        "ATOMIC_CMPXCHG_DW": 17,
        "ATOMIC_CMPXCHG_W": 8,
        "ATOMIC_OR_DW": 8,
        "ATOMIC_OR_FETCH_DW": 8,
        "ATOMIC_OR_FETCH_W": 8,
        "ATOMIC_OR_W": 8,
        "ATOMIC_XCHG_DW": 8,
        "ATOMIC_XCHG_W": 8,
        "ATOMIC_XOR_DW": 8,
        "ATOMIC_XOR_FETCH_DW": 8,
        "ATOMIC_XOR_FETCH_W": 8,
        "ATOMIC_XOR_W": 8,
        "DIV64_K": 46,
        "DIV64_X": 42,
        "DIV_K": 30,
        "DIV_X": 26,
        "EXIT": 2,
        "FADD64_K": 27,
        "FADD64_X": 23,
        "FADD_K": 27,
        "FADD_X": 23,
        "FDIV64_K": 132,
        "FDIV64_X": 128,
        "FDIV_K": 49,
        "FDIV_X": 45,
        "FLDX_B": 11,
        "FLDX_DW": 11,
        "FLDX_H": 11,
        "FLDX_W": 11,
        "FLD_B": 11,
        "FLD_DW": 11,
        "FLD_H": 11,
        "FLD_W": 11,
        "FMOV64_K": 15,
        "FMOV64_X": 15,
        "FMOV_K": 15,
        "FMOV_X": 15,
        "FMUL64_K": 104,
        "FMUL64_X": 100,
        "FMUL_K": 79,
        "FMUL_X": 75,
        "FNEG64_K": 15,
        "FNEG64_X": 15,
        "FNEG_K": 15,
        "FNEG_X": 15,
        "FSTX_B": 11,
        "FSTX_DW": 11,
        "FSTX_H": 11,
        "FSTX_W": 30,
        "FST_B": 11,
        "FST_DW": 11,
        "FST_H": 11,
        "FST_W": 11,
        "FSUB64_K": 27,
        "FSUB64_X": 23,
        "FSUB_K": 27,
        "FSUB_X": 23,
        "JA": 2,
        "JEQ32_K": 8,
        "JEQ32_X": 4,
        "JEQ_K": 8,
        "JEQ_X": 4,
        "JFEQ32_K": 22,
        "JFEQ32_X": 18,
        "JFEQ_K": 22,
        "JFEQ_X": 18,
        "JFNE32_K": 22,
        "JFNE32_X": 18,
        "JFNE_K": 22,
        "JFNE_X": 18,
        "JFOGE32_K": 22,
        "JFOGE32_X": 18,
        "JFOGE_K": 22,
        "JFOGE_X": 18,
        "JFOGT32_K": 22,
        "JFOGT32_X": 18,
        "JFOGT_K": 22,
        "JFOGT_X": 18,
        "JFOLE32_K": 22,
        "JFOLE32_X": 18,
        "JFOLE_K": 22,
        "JFOLE_X": 18,
        "JFOLT32_K": 22,
        "JFOLT32_X": 18,
        "JFOLT_K": 22,
        "JFOLT_X": 18,
        "JFUGE32_K": 22,
        "JFUGE32_X": 18,
        "JFUGE_K": 22,
        "JFUGE_X": 18,
        "JFUGT32_K": 22,
        "JFUGT32_X": 18,
        "JFUGT_K": 22,
        "JFUGT_X": 18,
        "JFULE32_K": 22,
        "JFULE_32X": 18,
        "JFULE_K": 22,
        "JFULE_X": 18,
        "JFULT32_K": 22,
        "JFULT32_X": 18,
        "JFULT_K": 22,
        "JFULT_X": 18,
        "JGE32_K": 8,
        "JGE32_X": 4,
        "JGE_K": 8,
        "JGE_X": 4,
        "JGT32_K": 8,
        "JGT32_X": 4,
        "JGT_K": 8,
        "JGT_X": 4,
        "JLE32_K": 8,
        "JLE32_X": 4,
        "JLE_K": 8,
        "JLE_X": 4,
        "JLT32_K": 8,
        "JLT32_X": 4,
        "JLT_K": 8,
        "JLT_X": 4,
        "JNE32_K": 8,
        "JNE32_X": 4,
        "JNE_K": 8,
        "JNE_X": 4,
        "JSET32_K": 10,
        "JSET32_X": 6,
        "JSET_K": 10,
        "JSET_X": 6,
        "JSGE32_K": 8,
        "JSGE32_X": 4,
        "JSGE_K": 8,
        "JSGE_X": 4,
        "JSGT32_K": 8,
        "JSGT32_X": 4,
        "JSGT_K": 8,
        "JSGT_X": 4,
        "JSLE32_K": 8,
        "JSLE32_X": 4,
        "JSLE_K": 8,
        "JSLE_X": 4,
        "JSLT32_K": 8,
        "JSLT32_X": 4,
        "JSLT_K": 8,
        "JSLT_X": 4,
        "LDDW": 27,
        "LDX_ABS_B": 11,
        "LDX_ABS_DW": 11,
        "LDX_ABS_H": 11,
        "LDX_ABS_W": 11,
        "LDX_B": 11,
        "LDX_DW": 11,
        "LDX_H": 11,
        "LDX_IMM_B": 11,
        "LDX_IMM_DW": 11,
        "LDX_IMM_H": 11,
        "LDX_IMM_W": 11,
        "LDX_IND_B": 11,
        "LDX_IND_DW": 11,
        "LDX_IND_H": 11,
        "LDX_IND_W": 11,
        "LDX_MEMSX_B": 11,
        "LDX_MEMSX_DW": 11,
        "LDX_MEMSX_H": 11,
        "LDX_MEMSX_W": 11,
        "LDX_W": 11,
        "LD_ABS_B": 11,
        "LD_ABS_DW": 11,
        "LD_ABS_H": 11,
        "LD_ABS_W": 11,
        "LD_IMM_B": 11,
        "LD_IMM_H": 11,
        "LD_IMM_W": 11,
        "LD_IND_B": 11,
        "LD_IND_DW": 11,
        "LD_IND_H": 11,
        "LD_IND_W": 11,
        "LD_MEMSX_B": 11,
        "LD_MEMSX_DW": 11,
        "LD_MEMSX_H": 11,
        "LD_MEMSX_W": 11,
        "LD_MEM_B": 11,
        "LD_MEM_DW": 11,
        "LD_MEM_H": 11,
        "LD_MEM_W": 11,
        "LSH64_K": 1,
        "LSH64_X": 8,
        "LSH_K": 1,
        "LSH_X": 8,
        "MOD64_K": 46,
        "MOD64_X": 42,
        "MOD_K": 30,
        "MOD_X": 26,
        "MOV64_K": 4,
        "MOV64_X": 2,
        "MOV_K": 4,
        "MOV_X": 2,
        "MUL64_K": 13,
        "MUL64_X": 9,
        "MUL_K": 12,
        "MUL_X": 8,
        "NEG64_K": 1,
        "NEG64_X": 1,
        "NEG_K": 1,
        "NEG_X": 1,
        "OR64_K": 20,
        "OR64_X": 8,
        "OR_K": 20,
        "OR_X": 8,
        "RSH64_K": 1,
        "RSH64_X": 8,
        "RSH_K": 1,
        "RSH_X": 8,
        "STX_ABS_B": 11,
        "STX_ABS_DW": 11,
        "STX_ABS_H": 11,
        "STX_ABS_W": 11,
        "STX_B": 11,
        "STX_DW": 30,
        "STX_H": 11,
        "STX_IMM_B": 11,
        "STX_IMM_DW": 11,
        "STX_IMM_H": 11,
        "STX_IMM_W": 11,
        "STX_IND_B": 11,
        "STX_IND_DW": 11,
        "STX_IND_H": 11,
        "STX_IND_W": 11,
        "STX_MEMSX_B": 11,
        "STX_MEMSX_DW": 11,
        "STX_MEMSX_H": 11,
        "STX_MEMSX_W": 11,
        "STX_W": 30,
        "ST_ABS_B": 11,
        "ST_ABS_DW": 11,
        "ST_ABS_H": 11,
        "ST_ABS_W": 11,
        "ST_B": 11,
        "ST_DW": 11,
        "ST_H": 11,
        "ST_IMM_B": 11,
        "ST_IMM_DW": 11,
        "ST_IMM_H": 11,
        "ST_IMM_W": 11,
        "ST_IND_B": 11,
        "ST_IND_DW": 11,
        "ST_IND_H": 11,
        "ST_IND_W": 11,
        "ST_MEMSX_B": 11,
        "ST_MEMSX_DW": 11,
        "ST_MEMSX_H": 11,
        "ST_MEMSX_W": 11,
        "ST_W": 11,
        "SUB64_K": 20,
        "SUB64_X": 8,
        "SUB_K": 20,
        "SUB_X": 8,
        "XOR64_K": 20,
        "XOR64_X": 8,
        "XOR_K": 20,
        "XOR_X": 8,
    },
)

# Bounding variants for WCET sensitivity analysis: same target (same clock, same
# instruction/latency_overrides), but every load is charged as a guaranteed L1 hit
# or a guaranteed miss instead of being classified by recency/associativity -- gives
# a best-case/worst-case bracket around NOELV_PROFILE's realistic estimate.
NOELV_ALL_HIT_PROFILE = replace(NOELV_PROFILE, name="noelv_all_hit", cache_mode="always_hit")
NOELV_ALL_MISS_PROFILE = replace(NOELV_PROFILE, name="noelv_all_miss", cache_mode="always_miss")
