from machine_profile import MachineProfile

# NOEL-V FPGA soft-core. Flat 2-level cache model (L1 associativity 4, L2 up to the
# full 12-entry recency window, no L3 tier), 100MHz clock, and 127 retuned
# per-instruction latencies (of 281 total; the rest match PolarFire's base bpf.py
# table). latency_overrides was mechanically regenerated from a diff between
# origin/Polarfire_test:bpf.py and origin/NOELV_test:bpf.py's InstrInfo(name, latency)
# pairs, not hand-transcribed.
NOELV_PROFILE = MachineProfile(
    name="noelv",
    latency=None,
    line_size_bytes=2,
    l1_associativity=4,
    l1_hit_cycles=13,
    l2_associativity=12,
    l2_hit_cycles=100,
    l3_associativity=None,
    l3_hit_cycles=None,
    miss_cycles=300,
    cpu_freq_hz=1e8,
    cache_size=12,
    default_helper_call_cost=150,
    latency_overrides={
        "ATOMIC_CMPXCHG_DW": 17,
        "DIV64_K": 19,
        "DIV64_X": 15,
        "DIV_K": 19,
        "DIV_X": 15,
        "FADD64_K": 20,
        "FADD64_X": 16,
        "FADD_K": 20,
        "FADD_X": 16,
        "FDIV64_K": 44,
        "FDIV64_X": 40,
        "FDIV_K": 44,
        "FDIV_X": 40,
        "FMOV64_K": 4,
        "FMOV64_X": 4,
        "FMOV_K": 4,
        "FMOV_X": 4,
        "FMUL64_K": 26,
        "FMUL64_X": 22,
        "FMUL_K": 26,
        "FMUL_X": 22,
        "FNEG64_K": 16,
        "FNEG64_X": 16,
        "FNEG_K": 16,
        "FNEG_X": 16,
        "FSUB64_K": 20,
        "FSUB64_X": 16,
        "FSUB_K": 20,
        "FSUB_X": 16,
        "JEQ32_K": 8,
        "JEQ32_X": 4,
        "JEQ_K": 8,
        "JEQ_X": 4,
        "JFEQ32_K": 22,
        "JFEQ32_X": 18,
        "JFEQ_K": 22,
        "JFEQ_X": 18,
        "JFNE32_K": 22,
        "JFNE32_X": 18,
        "JFNE_K": 22,
        "JFNE_X": 18,
        "JFOGE32_K": 22,
        "JFOGE32_X": 18,
        "JFOGE_K": 22,
        "JFOGE_X": 18,
        "JFOGT32_K": 22,
        "JFOGT32_X": 18,
        "JFOGT_K": 22,
        "JFOGT_X": 18,
        "JFOLE32_K": 22,
        "JFOLE32_X": 18,
        "JFOLE_K": 22,
        "JFOLE_X": 18,
        "JFOLT32_K": 22,
        "JFOLT32_X": 18,
        "JFOLT_K": 22,
        "JFOLT_X": 18,
        "JFUGE32_K": 22,
        "JFUGE32_X": 18,
        "JFUGE_K": 22,
        "JFUGE_X": 18,
        "JFUGT32_K": 22,
        "JFUGT32_X": 18,
        "JFUGT_K": 22,
        "JFUGT_X": 18,
        "JFULE32_K": 22,
        "JFULE_32X": 18,
        "JFULE_K": 22,
        "JFULE_X": 18,
        "JFULT32_K": 22,
        "JFULT32_X": 18,
        "JFULT_K": 22,
        "JFULT_X": 18,
        "JGE32_K": 8,
        "JGE32_X": 4,
        "JGE_K": 8,
        "JGE_X": 4,
        "JGT32_K": 8,
        "JGT32_X": 4,
        "JGT_K": 8,
        "JGT_X": 4,
        "JLE32_K": 8,
        "JLE32_X": 4,
        "JLE_K": 8,
        "JLE_X": 4,
        "JLT32_K": 8,
        "JLT32_X": 4,
        "JLT_K": 8,
        "JLT_X": 4,
        "JNE32_K": 8,
        "JNE32_X": 4,
        "JNE_K": 8,
        "JNE_X": 4,
        "JSET32_K": 10,
        "JSET32_X": 6,
        "JSET_K": 10,
        "JSET_X": 6,
        "JSGE32_K": 8,
        "JSGE32_X": 4,
        "JSGE_K": 8,
        "JSGE_X": 4,
        "JSGT32_K": 8,
        "JSGT32_X": 4,
        "JSGT_K": 8,
        "JSGT_X": 4,
        "JSLE32_K": 8,
        "JSLE32_X": 4,
        "JSLE_K": 8,
        "JSLE_X": 4,
        "JSLT32_K": 8,
        "JSLT32_X": 4,
        "JSLT_K": 8,
        "JSLT_X": 4,
        "MOD64_K": 19,
        "MOD64_X": 15,
        "MOD_K": 19,
        "MOD_X": 15,
        "MOV64_X": 2,
        "MOV_X": 2,
        "MUL64_K": 6,
        "MUL64_X": 2,
        "MUL_K": 6,
        "MUL_X": 2,
        "NEG64_K": 1,
        "NEG64_X": 1,
        "NEG_K": 1,
        "NEG_X": 1,
    },
)
