from dataclasses import replace
from machine_profile import MachineProfile

POLARFIRE_PROFILE = MachineProfile(
    name="polarfire",
    latency=None,
    line_size_bytes=4,
    l1_associativity=1,
    l1_hit_cycles=4,
    l2_associativity=1,
    l2_hit_cycles=16,
    l3_associativity=None,
    l3_hit_cycles=40,
    miss_cycles=210,
    cpu_freq_hz=6.67e8,
    cache_size=64,
    default_helper_call_cost=100,
    map_lookup_cycles=28,
    map_update_cycles=40,
    map_delete_cycles=10,
    iter_new_cycles=17,
    iter_next_cycles=19,
    iter_destroy_cycles=8,
    math_sqrt_cycles=43,
    math_sin_cycles=141,
    math_cos_cycles=122,
    math_atan2_cycles=327,
    latency_overrides={
        "ADD64_K": 21,
        "ADD64_X": 5,
        "ADD_K": 21,
        "ADD_X": 5,
        "AND64_K": 21,
        "AND64_X": 8,
        "AND_K": 21,
        "AND_X": 8,
        "ARSH64_K": 1,
        "ARSH64_X": 8,
        "ARSH_K": 1,
        "ARSH_X": 8,
        "ATOMIC_ADD_DW": 8,
        "ATOMIC_ADD_FETCH_DW": 8,
        "ATOMIC_ADD_FETCH_W": 8,
        "ATOMIC_ADD_W": 8,
        "ATOMIC_AND_DW": 8,
        "ATOMIC_AND_FETCH_DW": 8,
        "ATOMIC_AND_FETCH_W": 8,
        "ATOMIC_AND_W": 8,
        "ATOMIC_CMPXCHG_DW": 8,
        "ATOMIC_CMPXCHG_W": 8,
        "ATOMIC_OR_DW": 8,
        "ATOMIC_OR_FETCH_DW": 8,
        "ATOMIC_OR_FETCH_W": 8,
        "ATOMIC_OR_W": 8,
        "ATOMIC_XCHG_DW": 8,
        "ATOMIC_XCHG_W": 8,
        "ATOMIC_XOR_DW": 8,
        "ATOMIC_XOR_FETCH_DW": 8,
        "ATOMIC_XOR_FETCH_W": 8,
        "ATOMIC_XOR_W": 8,
        "DIV64_K": 71,
        "DIV64_X": 67,
        "DIV_K": 41,
        "DIV_X": 37,
        "EXIT": 2,
        "FADD64_K": 18,
        "FADD64_X": 11,
        "FADD_K": 16,
        "FADD_X": 9,
        "FDIV64_K": 65,
        "FDIV64_X": 58,
        "FDIV_K": 37,
        "FDIV_X": 30,
        "FLDX_B": 11,
        "FLDX_DW": 11,
        "FLDX_H": 11,
        "FLDX_W": 11,
        "FLD_B": 11,
        "FLD_DW": 11,
        "FLD_H": 11,
        "FLD_W": 11,
        "FMOV64_K": 9,
        "FMOV64_X": 9,
        "FMOV_K": 9,
        "FMOV_X": 9,
        "FMUL64_K": 19,
        "FMUL64_X": 12,
        "FMUL_K": 17,
        "FMUL_X": 10,
        "FNEG64_K": 51,
        "FNEG64_X": 51,
        "FNEG_K": 9,
        "FNEG_X": 9,
        "FSTX_B": 11,
        "FSTX_DW": 11,
        "FSTX_H": 11,
        "FSTX_W": 11,
        "FST_B": 11,
        "FST_DW": 11,
        "FST_H": 11,
        "FST_W": 11,
        "FSUB64_K": 18,
        "FSUB64_X": 11,
        "FSUB_K": 17,
        "FSUB_X": 10,
        "JA": 2,
        "JEQ32_K": 7,
        "JEQ32_X": 3,
        "JEQ_K": 7,
        "JEQ_X": 3,
        "JFEQ32_K": 10,
        "JFEQ32_X": 3,
        "JFEQ_K": 10,
        "JFEQ_X": 3,
        "JFNE32_K": 10,
        "JFNE32_X": 3,
        "JFNE_K": 10,
        "JFNE_X": 3,
        "JFOGE32_K": 10,
        "JFOGE32_X": 3,
        "JFOGE_K": 10,
        "JFOGE_X": 3,
        "JFOGT32_K": 10,
        "JFOGT32_X": 3,
        "JFOGT_K": 10,
        "JFOGT_X": 3,
        "JFOLE32_K": 10,
        "JFOLE32_X": 3,
        "JFOLE_K": 10,
        "JFOLE_X": 3,
        "JFOLT32_K": 10,
        "JFOLT32_X": 3,
        "JFOLT_K": 10,
        "JFOLT_X": 3,
        "JFUGE32_K": 15,
        "JFUGE32_X": 8,
        "JFUGE_K": 15,
        "JFUGE_X": 8,
        "JFUGT32_K": 15,
        "JFUGT32_X": 8,
        "JFUGT_K": 15,
        "JFUGT_X": 8,
        "JFULE32_K": 15,
        "JFULE_32X": 13,
        "JFULE_K": 15,
        "JFULE_X": 13,
        "JFULT32_K": 15,
        "JFULT32_X": 8,
        "JFULT_K": 15,
        "JFULT_X": 8,
        "JGE32_K": 7,
        "JGE32_X": 3,
        "JGE_K": 7,
        "JGE_X": 3,
        "JGT32_K": 7,
        "JGT32_X": 3,
        "JGT_K": 7,
        "JGT_X": 3,
        "JLE32_K": 7,
        "JLE32_X": 3,
        "JLE_K": 7,
        "JLE_X": 3,
        "JLT32_K": 7,
        "JLT32_X": 3,
        "JLT_K": 7,
        "JLT_X": 3,
        "JNE32_K": 7,
        "JNE32_X": 3,
        "JNE_K": 7,
        "JNE_X": 3,
        "JSET32_K": 8,
        "JSET32_X": 4,
        "JSET_K": 8,
        "JSET_X": 4,
        "JSGE32_K": 7,
        "JSGE32_X": 3,
        "JSGE_K": 7,
        "JSGE_X": 3,
        "JSGT32_K": 7,
        "JSGT32_X": 3,
        "JSGT_K": 7,
        "JSGT_X": 3,
        "JSLE32_K": 7,
        "JSLE32_X": 3,
        "JSLE_K": 7,
        "JSLE_X": 3,
        "JSLT32_K": 7,
        "JSLT32_X": 3,
        "JSLT_K": 7,
        "JSLT_X": 3,
        "LDDW": 11,
        "LDX_ABS_B": 11,
        "LDX_ABS_DW": 11,
        "LDX_ABS_H": 11,
        "LDX_ABS_W": 11,
        "LDX_B": 11,
        "LDX_DW": 11,
        "LDX_H": 11,
        "LDX_IMM_B": 11,
        "LDX_IMM_DW": 11,
        "LDX_IMM_H": 11,
        "LDX_IMM_W": 11,
        "LDX_IND_B": 11,
        "LDX_IND_DW": 11,
        "LDX_IND_H": 11,
        "LDX_IND_W": 11,
        "LDX_MEMSX_B": 11,
        "LDX_MEMSX_DW": 11,
        "LDX_MEMSX_H": 11,
        "LDX_MEMSX_W": 11,
        "LDX_W": 11,
        "LD_ABS_B": 11,
        "LD_ABS_DW": 11,
        "LD_ABS_H": 11,
        "LD_ABS_W": 11,
        "LD_IMM_B": 11,
        "LD_IMM_H": 11,
        "LD_IMM_W": 11,
        "LD_IND_B": 11,
        "LD_IND_DW": 11,
        "LD_IND_H": 11,
        "LD_IND_W": 11,
        "LD_MEMSX_B": 11,
        "LD_MEMSX_DW": 11,
        "LD_MEMSX_H": 11,
        "LD_MEMSX_W": 11,
        "LD_MEM_B": 11,
        "LD_MEM_DW": 11,
        "LD_MEM_H": 11,
        "LD_MEM_W": 11,
        "LSH64_K": 1,
        "LSH64_X": 8,
        "LSH_K": 1,
        "LSH_X": 8,
        "MOD64_K": 71,
        "MOD64_X": 67,
        "MOD_K": 41,
        "MOD_X": 37,
        "MOV64_K": 4,
        "MOV64_X": 4,
        "MOV_K": 4,
        "MOV_X": 4,
        "MUL64_K": 14,
        "MUL64_X": 10,
        "MUL_K": 14,
        "MUL_X": 10,
        "NEG64_K": 0,
        "NEG64_X": 0,
        "NEG_K": 0,
        "NEG_X": 0,
        "OR64_K": 21,
        "OR64_X": 8,
        "OR_K": 21,
        "OR_X": 8,
        "RSH64_K": 1,
        "RSH64_X": 8,
        "RSH_K": 1,
        "RSH_X": 8,
        "STX_ABS_B": 11,
        "STX_ABS_DW": 11,
        "STX_ABS_H": 11,
        "STX_ABS_W": 11,
        "STX_B": 11,
        "STX_DW": 11,
        "STX_H": 11,
        "STX_IMM_B": 11,
        "STX_IMM_DW": 11,
        "STX_IMM_H": 11,
        "STX_IMM_W": 11,
        "STX_IND_B": 11,
        "STX_IND_DW": 11,
        "STX_IND_H": 11,
        "STX_IND_W": 11,
        "STX_MEMSX_B": 11,
        "STX_MEMSX_DW": 11,
        "STX_MEMSX_H": 11,
        "STX_MEMSX_W": 11,
        "STX_W": 11,
        "ST_ABS_B": 11,
        "ST_ABS_DW": 11,
        "ST_ABS_H": 11,
        "ST_ABS_W": 11,
        "ST_B": 11,
        "ST_DW": 11,
        "ST_H": 11,
        "ST_IMM_B": 11,
        "ST_IMM_DW": 11,
        "ST_IMM_H": 11,
        "ST_IMM_W": 11,
        "ST_IND_B": 11,
        "ST_IND_DW": 11,
        "ST_IND_H": 11,
        "ST_IND_W": 11,
        "ST_MEMSX_B": 11,
        "ST_MEMSX_DW": 11,
        "ST_MEMSX_H": 11,
        "ST_MEMSX_W": 11,
        "ST_W": 11,
        "SUB64_K": 21,
        "SUB64_X": 8,
        "SUB_K": 21,
        "SUB_X": 8,
        "XOR64_K": 21,
        "XOR64_X": 8,
        "XOR_K": 21,
        "XOR_X": 8,
    },
)

POLARFIRE_ALL_HIT_PROFILE = replace(POLARFIRE_PROFILE, name="polarfire_all_hit", cache_mode="always_hit")
POLARFIRE_ALL_MISS_PROFILE = replace(POLARFIRE_PROFILE, name="polarfire_all_miss", cache_mode="always_miss")
